"""Read/write the sanitized pfSense ruleset as YAML (rules.yaml).

This is the bridge that lets the full pfSense config.xml backup (which contains
secrets) stay out of the running app. An offline extract step writes just the
firewall rules + interface map here; the correlation detector reads it at runtime.
"""

from dataclasses import asdict
from typing import Dict, List, Tuple

import yaml

from .pfsense import PFRule

_HEADER = (
    "# GENERATED by `python -m src.tools.extract_pfsense` — do not edit by hand.\n"
    "# Sanitized extract of a pfSense config.xml backup (rules + interface map only).\n"
    "# Regenerate whenever your firewall rules change.\n"
)


def dump_ruleset(rules: List[PFRule], interfaces: Dict[str, str], path: str) -> None:
    """Write the interface map and firewall rules to a YAML file."""
    data = {
        "interfaces": dict(interfaces),
        "rules": [asdict(r) for r in rules],
    }
    with open(path, "w", encoding="utf-8") as f:
        f.write(_HEADER)
        yaml.safe_dump(data, f, sort_keys=False, default_flow_style=False)


def load_ruleset(path: str) -> Tuple[List[PFRule], Dict[str, str]]:
    """Load (rules, interface_map) from a generated rules.yaml file."""
    with open(path, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}

    interfaces = data.get("interfaces") or {}
    rules = [PFRule(**r) for r in (data.get("rules") or [])]
    return rules, interfaces
