"""Read/write the sanitized pfSense ruleset as YAML (rules.yaml).

This is the bridge that lets the full pfSense config.xml backup (which contains
secrets) stay out of the running app. An offline extract step writes just the
firewall rules, alias table, and interface map here; the correlation detector
reads it at runtime.

The WRITE side (dump_ruleset) is pure-stdlib so the extract command runs on any
host with only python3 — no pyyaml, no pip. The READ side (load_ruleset) lazily
imports pyyaml, which is only needed where rules.yaml is consumed (the container).
"""

from dataclasses import asdict
from typing import Dict, List, Tuple

from .pfsense import PFRule

_HEADER = (
    "# GENERATED by `python -m src.tools.extract_pfsense` — do not edit by hand.\n"
    "# Sanitized extract of a pfSense config.xml backup (rules, aliases, interfaces).\n"
    "# Regenerate whenever your firewall rules change.\n"
)


def _scalar(value) -> str:
    """Render a Python scalar as YAML (stdlib only)."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    text = (
        str(value)
        .replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace("\r", "\\r")
    )
    return '"' + text + '"'


def _emit(obj, indent: int) -> List[str]:
    """Emit a dict/list/scalar tree as block-style YAML lines (stdlib only)."""
    pad = "  " * indent
    lines: List[str] = []

    if isinstance(obj, dict):
        for key, value in obj.items():
            if isinstance(value, (dict, list)) and value:
                lines.append(f"{pad}{key}:")
                lines.extend(_emit(value, indent + 1))
            elif isinstance(value, dict):
                lines.append(f"{pad}{key}: {{}}")
            elif isinstance(value, list):
                lines.append(f"{pad}{key}: []")
            else:
                lines.append(f"{pad}{key}: {_scalar(value)}")
    elif isinstance(obj, list):
        for item in obj:
            if isinstance(item, dict) and item:
                inner = _emit(item, indent + 1)
                lines.append(f"{pad}- {inner[0].strip()}")
                lines.extend(inner[1:])
            elif isinstance(item, (dict, list)):
                lines.append(f"{pad}- {'{}' if isinstance(item, dict) else '[]'}")
            else:
                lines.append(f"{pad}- {_scalar(item)}")
    return lines


def dump_ruleset(
    rules: List[PFRule],
    interfaces: Dict[str, dict],
    aliases: Dict[str, dict],
    path: str,
) -> None:
    """Write interfaces, aliases, and firewall rules to a YAML file (stdlib only)."""
    data = {
        "interfaces": dict(interfaces),
        "aliases": dict(aliases),
        "rules": [asdict(r) for r in rules],
    }
    with open(path, "w", encoding="utf-8") as f:
        f.write(_HEADER)
        f.write("\n".join(_emit(data, 0)) + "\n")


def load_ruleset(path: str) -> Tuple[List[PFRule], Dict[str, dict], Dict[str, dict]]:
    """Load (rules, interfaces, aliases) from a generated rules.yaml file."""
    import yaml  # lazy: only needed where rules.yaml is consumed

    with open(path, encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}

    interfaces = data.get("interfaces") or {}
    aliases = data.get("aliases") or {}
    rules = [PFRule(**r) for r in (data.get("rules") or [])]
    return rules, interfaces, aliases
