services:
  netmon:
    build: .
    container_name: netmon
    ports:
      - "514:514/udp"
    volumes:
      - netmon-data:/data
      - ./settings.yaml:/app/settings.yaml:ro
      - ./rules.yaml:/config/rules.yaml:ro
    restart: unless-stopped

volumes:
  netmon-data:
